version: "3.8"

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: ${BUILD_TARGET:-development}  # デフォルトはfull development環境
    container_name: wantedly-dev
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    network_mode: service:wantedly-db
    environment:
      - PGPASSWORD=wantedly
      - PGUSER=wantedly
      - PGDATABASE=wantedly
      - PGHOST=wantedly-db

  wantedly-db:
    image: postgres:16
    container_name: wantedly-db
    restart: unless-stopped
    volumes:
      - wantedly-db-data:/var/lib/postgresql/data
    ports:
      - 50010:5432
    environment:
      - POSTGRES_USER=wantedly
      - POSTGRES_PASSWORD=wantedly
      - POSTGRES_DB=wantedly

volumes:
  wantedly-db-data:
    name: wantedly-db-data
