name: develop
version: '3'

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: ${BUILD_TARGET:-development}  # デフォルトはfull development環境
    container_name: develop-dev
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    networks:
      - develop-network
    environment:
      - PGPASSWORD=develop
      - PGUSER=develop
      - PGDATABASE=develop
      - PGHOST=develop-db

  develop-db:
    image: postgres:16
    container_name: develop-db
    restart: unless-stopped
    volumes:
      - develop-db-data:/var/lib/postgresql/data
    ports:
      - 50015:5432
    environment:
      - POSTGRES_USER=develop
      - POSTGRES_PASSWORD=develop
      - POSTGRES_DB=develop
    networks:
      - develop-network

volumes:
  develop-db-data:
    name: develop-db-data

networks:
  develop-network:
    name: develop-network