version: "3.8"

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: ${BUILD_TARGET:-development}  # デフォルトはfull development環境
    container_name: monelite-dev
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    network_mode: service:monelite-db
    environment:
      - PGPASSWORD=monelite
      - PGUSER=monelite
      - PGDATABASE=monelite
      - PGHOST=monelite-db

  monelite-db:
    image: postgres:16
    container_name: monelite-db
    restart: unless-stopped
    volumes:
      - monelite-db-data:/var/lib/postgresql/data
    ports:
      - 50010:5432
    environment:
      - POSTGRES_USER=monelite
      - POSTGRES_PASSWORD=monelite
      - POSTGRES_DB=monelite

volumes:
  monelite-db-data:
    name: monelite-db-data
