version: "3.8"

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: investwise-dev
    volumes:
      - ../..:/workspaces:cached

    command: sleep infinity

    network_mode: service:investwise-db

    environment:
      - PGPASSWORD=test
      - PGUSER=test
      - PGDATABASE=test
      - PGHOST=investwise-db

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  investwise-db:
    image: postgres:16
    container_name: investwise-db
    restart: unless-stopped
    volumes:
      - investwise-db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test

volumes:
  investwise-db-data:
    name: investwise-db-data